### ISSUE TITLE
Print the name of the service token in application access logs

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#114]
## Is your feature request related to a problem?

Currently all log events created by Service Tokens are displayed as `🔑 Service token` which makes it hard to trace access.

![image](https://github.com/phasehq/console/assets/85357445/95f04871-4fb7-47e1-bc2d-e8122adab5ea)

## Describe the solution you'd like

1. Display the name of the actual Service Token used to access secrets in the logs
2. Provide a link to similar to `View this secret` to view the Service Token in the App > Service Tokens screen

![image](https://github.com/phasehq/console/assets/85357445/457276d0-b131-4c5a-b619-4eccc312e2a3)

**Comment by Dhoni77** [comment]
Hi @nimish-ks I would like to work on this

**Comment by nimish-ks** [comment]
@Dhoni77 All yours! You can reach out to use on slack if you need any context -- https://slack.phase.dev

**Comment by rohan-chaturvedi** [comment]
@Dhoni77 Here's some more context on implementing this:
The `SecretEvent` model is what we use to track CRUD changes to Secrets: https://github.com/phasehq/console/blob/f63640b21400d2b2305cd359f8f05abdf9082f74/backend/api/models.py#L309 

As you can see, there's a `user` foreign key. If this `user` key is null, we assume this event was created by a service token. Instead, we need to create an additionally, nullable 'token' foreign key for the Service Token model: https://github.com/phasehq/console/blob/f63640b21400d2b2305cd359f8f05abdf9082f74/backend/api/models.py#L243
 
Then, we'll need to handle the following:
* Update graphql types: https://github.com/phasehq/console/blob/f63640b21400d2b2305cd359f8f05abdf9082f74/backend/backend/graphene/types.py#L161
* Update the frontend queries for logs and display the token name instead of 'Service token': https://github.com/phasehq/console/blob/f63640b21400d2b2305cd359f8f05abdf9082f74/frontend/components/logs/SecretLogs.tsx#L264
* Make sure the token is logged for each type of CRUD event via the REST api: https://github.com/phasehq/console/blob/f63640b21400d2b2305cd359f8f05abdf9082f74/backend/api/views.py#L294

As Nimish, said, feel free to join our Slack if you'd like any more context or have any questions!

**Comment by nishaaannnt** [comment]
Hello, @rohan-chaturvedi , we would like to work on this issue under Fosshack 2024. 
Me and my teammate @viku3150 are well versed with the tech stack and the codebase and hence would like to take this forward. 
Please assign us for the same. 
Thank you.

**Comment by nishaaannnt** [comment]
<img width="948" alt="Screenshot 2024-07-27 at 1 55 14 PM" src="https://github.com/user-attachments/assets/64dc0bb7-57d4-40b3-a892-9c6aac2aa716">
@nimish-ks @rohan-chaturvedi  Done. Was trying to recreate the issue and found it done.

**Comment by rohan-chaturvedi** [comment]
> <img alt="Screenshot 2024-07-27 at 1 55 14 PM" width="948" src="https://private-user-images.githubusercontent.com/100792085/352710157-64dc0bb7-57d4-40b3-a892-9c6aac2aa716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjk1OTEsIm5iZiI6MTcyMjA2OTI5MSwicGF0aCI6Ii8xMDA3OTIwODUvMzUyNzEwMTU3LTY0ZGMwYmI3LTU3ZDQtNDBiMy1hODkyLTljNmFhYzJhYTcxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwODM0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjk3M2JiZWVhYzRhZjZiNmUzNWVhYzZkYTAzNTE5ZDI0MDM0MmU3OGQzMTM5MTIwZjFkMGM3MzcyNjZlNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9dg_aw1rEU0lY2cQv2gqVvExUdWyduu4QhqH-IGtdj0"> @nimish-ks @rohan-chaturvedi Done. Was trying to recreate the issue and found it done. Also got it verified on call with @nimish-ks

Great!
