### ISSUE TITLE
Improve the unlock keyring popup

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#131]
## Describe the solution you'd like

![image](https://github.com/phasehq/console/assets/85357445/23ecc6bf-346e-474f-8bf4-0df46aa2da55)
- Add a button that users can click to gracefully back of the unlock keyring popup
![image](https://github.com/phasehq/console/assets/85357445/19898957-d44d-4aed-8950-3b921ceba43b)
- Add a badge indicator in the status bar on the top right of the screen to indicate weather the keyring is locked or not

**Comment by rohan-chaturvedi** [comment]
> Add a button that users can click to gracefully back of the unlock keyring popup

This isn't really possible, because several screens require the keyring to be unlocked in order to render anything. The popup cannot be closed or dismissed intentionally, because there isn't any real UI we can render if you do. Users can always hit "back" in the browser if they want.

> Add a badge indicator in the status bar on the top right of the screen to indicate weather the keyring is locked or not

Played with this idea, but its mostly useless because we don't let users manually lock / unlock the keyring whenever they want to. If / when we allow that, it would make more sense.
