### ISSUE TITLE
Changes to secret path are not correctly display in history dialog

### ISSUE THREAD

**Issue by rohan-chaturvedi** [phasehq/console#194]
### Describe the bug

When a secret's path is updated via the CLI / API / SDK, an update event is shown in the UI but the diff of the previous vs current path is not shown

### To Reproduce

1. Create a secret
2. Update its path
3. View secret history in Console

### Expected behavior

The difference between the previous and current path should be displayed

### Screenshots

![image](https://github.com/phasehq/console/assets/6710327/f41d9c0a-62ba-4cb7-9871-0d368c8ff399)

**Comment by teyim** [comment]
@rohan-chaturvedi i'll like to look at this.

**Comment by nishaaannnt** [comment]
Hello, @rohan-chaturvedi , we would like to work on this issue under Fosshack 2024. 
Me and my teammate @viku3150 are well versed with the tech stack and the codebase and hence would like to take this forward. 
Please assign us for the same. 
Thank you.

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi can you tell me what do you mean by update path? Does it mean to update the value of the key? 
maybe I am missing something. Can you guide me on how to update the path. Thanks!

**Comment by rohan-chaturvedi** [comment]
@nishaaannnt I mean the `path` attribute of a secret, i.e which folder the secret is in. Currently the path can only be updated via the REST API though, as there is no way to do this via the UI.  The API docs should give more context: https://docs.phase.dev/public-api/secrets#update-secrets

**Comment by nishaaannnt** [comment]
@rohan-chaturvedi 
<img width="553" alt="Screenshot 2024-07-27 at 7 06 30 PM" src="https://github.com/user-attachments/assets/a856c22d-11f2-4a33-8255-d3f2ba4e835a">
Let me know your thoughts. Fixed it. Took a lot of time to figure out the backend but was worth it. Also added a spacing between green and red, because it looks better, if you like can add the same spacing to other changes like comment, key etc. 
For spacing used {" "} .

**Comment by rohan-chaturvedi** [comment]
Looks great!
