### ISSUE TITLE
Improve app deletetion screen

### ISSUE THREAD

**Issue by nimish-ks** [phasehq/console#35]
![image](https://github.com/phasehq/console/assets/85357445/8fc31191-06d8-4be3-86d1-c20e0b43f6ec)

Suggestions:
- Require sudo password for app deletion, don't solely rely on SSO authentication
- Change the color of the 'delete' button from green to red

**Comment by rohan-chaturvedi** [comment]
Agreed on the color change for the button, since delete is a destructive action.  Regarding the sudo password, we should request it but we will need to think about how we will verify it. Currently we only ask for the sudo password when decrypting the local keyring is required. Technically we don't need to decrypt the keyring to remove an app key, so we would have to just check that we were able to successfully decrypt it as way of verifying the password.
